# Generated by Django 4.2.7 on 2023-11-06 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('BIN', models.CharField(max_length=100, verbose_name='BIN')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('phone', models.CharField(max_length=100, verbose_name='phone')),
                ('fax', models.CharField(blank=True, max_length=100, null=True, verbose_name='fax')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('web_site', models.CharField(blank=True, max_length=100, null=True, verbose_name='web site')),
            ],
            options={
                'verbose_name': 'finOrganization',
                'verbose_name_plural': 'finOrganizations',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='full_name')),
                ('IIN', models.CharField(max_length=100, verbose_name='IIN')),
                ('job_title', models.CharField(max_length=300, verbose_name='job title')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='phone')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('fin_organization', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='web.financialorganization', verbose_name='fin organization')),
            ],
            options={
                'verbose_name': 'manager',
                'verbose_name_plural': 'managers',
            },
        ),
    ]
