# Generated by Django 4.2.7 on 2023-11-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='job_title',
            field=models.CharField(choices=[('Председатель Совета директоров', 'Председатель Совета директоров'), ('Председатель Правления', 'Председатель Правления'), ('Совет директоров', 'Совет директоров'), ('Члены Правления', 'Члены Правления'), ('Главный бухгалтер', 'Главный бухгалтер')], default='Главный бухгалтер', max_length=300),
        ),
    ]
