# Generated by Django 4.2.7 on 2023-11-09 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_manager_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='full_name')),
                ('IIN', models.CharField(max_length=100, verbose_name='IIN')),
                ('job_title', models.CharField(choices=[('Председатель Совета директоров', 'Председатель Совета директоров'), ('Председатель Правления', 'Председатель Правления'), ('Совет директоров', 'Совет директоров'), ('Члены Правления', 'Члены Правления'), ('Главный бухгалтер', 'Главный бухгалтер')], default='Главный бухгалтер', max_length=300)),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='phone')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('fin_organization', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='executives', to='web.financialorganization', verbose_name='fin organization')),
            ],
            options={
                'verbose_name': 'executive',
                'verbose_name_plural': 'executives',
            },
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
