# Generated by Django 4.2.7 on 2023-11-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_workperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workperiod',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='Created on'),
        ),
    ]
