# Generated by Django 4.2.7 on 2023-11-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_workperiod_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workperiod',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created on'),
        ),
    ]
